routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('raiz');

Route::get('/empresas/registro','EmpresasController@index')->name('registroEmpresas');
Route::get('/institucion/registro','InstitucionController@index')->name('registroInstituciones');
Route::get('/estudiantes/registro','EstudianteController@index')->name('registroEstudiantes');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('institucion', 'InstitucionController');
Route::resource('estudiantes', 'EstudianteController');
Route::post('/estudiantes/importar','EstudianteController@importar')->name('importarEstudiantes');
Route::resource('empresas', 'EmpresasController');
Route::post('/empresas/importar','EmpresasController@importar')->name('importarEmpresas');
Route::resource('convenios', 'ConveniosController');
Route::resource('users', 'UsersController');

Route::post('/empresas/invitacion','EmpresasController@mailInvitacion')->name('InvitacionEmpresas');
Route::post('/institucion/invitacion','InstitucionController@mailInvitacion')->name('InvitacionInstitucion');

Route::resource('mensajeria','MensajeriaController');
Route::resource('asignacion','AsignarEstudianteController');
Route::resource('configuracionPasos','ConfiguracionPasosController');

Route::resource('evaluar-practicante','EvaluacionPracticanteController');

Route::get('asistencia-practicante/{id}','AsistenciaPracticanteController@index');
Route::resource('asistencia-practicante','AsistenciaPracticanteController');

Route::get('retiro-practicante/{id}','RetirarPracticanteController@index');
Route::resource('retiro-practicante','RetirarPracticanteController');

Route::get('observacion-practicante/{id}','ObservacionPracticanteController@index');
Route::resource('observacion-practicante','ObservacionPracticanteController');

Route::get('anexar-doc-practicantes/{id}','AnexarARLPracticanteController@index');
Route::resource('anexar-doc-practicantes','AnexarARLPracticanteController');


Route::get('mi-perfil','MiPerfilController@index')->name('miPerfil.index');
Route::post('mi-perfil','MiPerfilController@update')->name('miPerfil.update');

Route::resource('solicitud-practicantes','SolicitudesPracticantes');
Route::resource('encuestas','EncuestasController');


Route::resource('dependencias','DependenciasController');
Route::resource('sucursales','SucursalesController');
Route::resource('funcionarios','FuncionariosController');
Route::resource('cupos-practicas','CuposPracticasController');
Route::resource('documentos-legales','DocumentosLegalesController');

Route::post('cupos-practicas/importar','CuposPracticasController@importar')->name('cupos-practicas.importar');
Route::get('gestion-practicas','GestionPracticasController@index')->name('gestion-practicas.index');

Route::get('estudiantes-disponibles','EstudiantesDisponiblesController@index')->name('estudiantes-disponibles.index');
Route::post('estudiantes-disponibles','EstudiantesDisponiblesController@solicitudCupo')->name('estudiantes-disponibles.solicitudCupo');

Route::post('estudiantes-disponiblesRem','EstudiantesDisponiblesController@solicitudCupoRemplazo')->name('estudiantes-disponiblesRem.solicitudCupoRemplazo');

Route::get('estudiantes-preseleccionados','EstudiantesPreseleccionadosController@index')->name('estudiantes-preseleccionados.index');

// Route::get('proceso-seleccion/{idependencia}','ProcesoSeleccionController@index');
Route::get('proceso-seleccion/{idestudiante}/{idependencia}','ProcesoSeleccionController@index');
Route::post('proceso-seleccion','ProcesoSeleccionController@store')->name('proceso-seleccion.store');
Route::post('proceso-seleccion/update/{id}','ProcesoSeleccionController@update')->name('proceso-seleccion.update');
Route::post('proceso-seleccion/noseleccionar','ProcesoSeleccionController@noselect')->name('proceso-seleccion.noselect');
Route::post('proceso-seleccion/seleccionar','ProcesoSeleccionController@select')->name('proceso-seleccion.select');


Route::get('estudiantes-seleccionados','EstudiantesSeleccionadosController@index')->name('estudiantes-seleccionados.index');
Route::get('estudiantes-seleccionados-info/{id}/{idseleccionado}','EstudiantesSeleccionadosInfoController@index');

Route::get('estudiantes-solicitados', 'EstudiantesSolicitados@index')->name('estudiantes-solicitados.index');
Route::post('estudiantes-solicitados', 'EstudiantesSolicitados@cambiarEstado')->name('estudiantes-solicitados.cambiarEstado');

Route::resource('programas','ProgramasController');
Route::post('programas/importar', 'ProgramasController@importar')->name('importarProgramas');

Route::get('recuperar-contrasena/{identificacion}', 'UsersController@password')->name('recuperar-contrasena');
Route::get('nueva-contrasena/{identificacion}', 'UsersController@nuevaContrasena')->name('nueva-contrasena');
Route::post('guardar-contrasena', 'UsersController@guardarContrasena')->name('guardar-contrasena');

Route::post('documento-convenio/{convenio}','ConveniosController@guardarDocumento')->name('documento-convenio');

resources/views/dependencias.blade.php
@extends('layouts.site')

@section('title')
    Dependencias
@endsection

@section('content')
<div id="page-title">
    <h2>Dependencias</h2>
</div>
<div class="panel">
    <div class="panel-body">
    	<div class="row">
            <div class="col-md-12 mrg20B text-right">
                <button class="btn btn-alt btn-hover btn-primary" data-target="#mdlCrear" onclick="abrirModal(this)">
                        <span>Nuevo</span>
                        <i class="glyph-icon icon-plus"></i>
                </button>
            </div>
        </div>
        {{-- Modal Creacion --}}
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="mdlCrear">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Nueva Dependencia</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{ route('dependencias.store') }}" id="frmCrearDependencia">
                            @csrf
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3">
                                    <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" name="txtNombre" class="form-control" autocomplete="off">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-primary" onclick="$('#frmCrearDependencia').submit()">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
        {{-- Modal Creacion --}}

        {{-- Modal editar --}}
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="mdlEditar">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Editar Dependencia</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{ route('dependencias.update','') }}" id="frmEditarDependencia">
                            @csrf
                            {{method_field('PUT')}}
                            <input type="hidden" name="hdDependenciaId" id="hdDependenciaId">
                            <div class="row">
                                <div class="col-md-6 col-md-offset-2">
                                    <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" name="txtNombre" id="txtNombreEdit" class="form-control" autocomplete="off">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label">Estado</label>
                                        <input type="checkbox" name="chkEstado" id="chkEstado" class="input-switch-alt">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-primary" onclick="$('#frmEditarDependencia').submit()">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
        {{-- Modal editar --}}

        {{-- tabla --}}
        <div class="example-box-wrapper">
            <input type="hidden" id="hdEmpresa" value="{{ Auth::user()->tercero_id }}">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="datatable-example">
            <thead>
            <tr>
                <th>Dependencia</th>
                <th>Estado</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            
            </tbody>
            </table>
        </div>
        {{-- end tabla --}}
    </div>
</div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ asset('template/widgets/datatable/datatable.js') }}"></script>
    <script type="text/javascript" src="{{ asset('template/widgets/datatable/datatable-bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('template/widgets/datatable/datatable-tabletools.js') }}"></script>
    <script type="text/javascript" src="{{ asset('template/widgets/jgrowl-notifications/jgrowl.js') }}"></script>
    <script type="text/javascript" src="{{ asset('template/widgets/datepicker/datepicker.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/dependencias.js') }}"></script>
@endsection

resources/views/estudiantesSeleccionadosInfo.blade.php
@extends('layouts.site')

@section('title')
    Estudiante Seleccionado
@endsection

@section('content')

<div id="page-title" style="display: flex; margin-bottom: 10px;">
    <h2>Estudiante Seleccionado</h2>
    <a href="{{ route('estudiantes-seleccionados.index') }}" style="margin-bottom: auto;margin-top: auto;margin-left: auto;font-size: 1.2em;text-decoration: none;color: black;cursor: pointer;"> 
            <i class="glyph-icon icon-arrow-left"></i>
        Volver
    </a>
</div>

<div class="panel">
    <div class="panel-body">
        <input type="hidden" id="hdEmpresa" value="{{ Auth::user()->tercero_id }}">
        <input type="hidden" id="idEstudiante" value="{{ $idestudiante }}">
        <input type="hidden" id="idseleccionado" name="{{ $idseleccionado }}">
       <div class="row">
           <div class="col-md-2">
               <img class="img-thumbnail" id="foto" src="" width="100"><br>
           </div>
           <div class="col-md-10">
               <strong>Matricula-Codigo:</strong> 3572 <br>
               <strong>Identificación:</strong> <span id="cedula"></span><br>
               <strong>Nombre:</strong> <span id="nombres"></span><br>
               <strong>Programa:</strong><span id="programa"></span>
           </div>
       </div>
       <div class="example-box-wrapper mrg20T">
            <ul class="nav-responsive nav nav-tabs">
                <li class="active"><a href="#tab1" data-toggle="tab">Datos Personales</a></li>
                <li><a href="#tab2" data-toggle="tab">Referencias Personales</a></li>
                <li><a href="#tab3" data-toggle="tab">Modulos</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">
                    <!-- <p>Datos Personales</p> -->
                    <div class="example-box-wrapper" style="display: flex;">
                        
                        <table class="table" style="width: 60% !important;">
                        <tbody>
                            <tr>
                                <td>Grupo Sanguineo:</td>
                                <td id="sangre"></td>
                            </tr>
                            <tr>
                                <td>Telefono/celular:</td>
                                <td id="telefono"></td>
                            </tr>
                            <tr>
                                <td>Dirección:</td>
                                <td id="direccion"></td>

                            </tr>
                            <tr>
                                <td>Correo:</td>
                                <td id="correo"></td>
                                
                            </tr>
                            <tr>
                                <td>Fecha de Inicio:</td>
                                <td>Ciclo B - 8 de Agosto de 2020</td>
                                
                            </tr>
                            <tr>
                                <td>Horario de clases:</td>
                                <td>10:00 Am a 12:15 Pm</td>
                                
                            </tr>
                            <tr>
                                <td>Modulo Actual:</td>
                                <td>5</td>
                                
                            </tr>
                            <tr>
                                <td>Modulos Pendientes:</td>
                                <td>2</td>
                                
                            </tr>
                            <tr>
                                <td>Hoja de Vida:</td>
                                <td> 
                                    <i class="textos-info glyph-icon icon-file-text-o" style="margin-right:2px;"></i>
                                    <span>Hoja de Vida</span>
                                </td>
                                
                            </tr>
                            <tr>
                                <td>Ciclo Aprobación:</td>
                                <td>Paz y Salvo Administrativo<br>Prueba Psicotécnicas</td>
                                
                            </tr>
                            <tr>
                                <td>Lugar:</td>
                                <td>Centro Inca - Sede Principal</td>
                                
                            </tr>
                            <tr>
                                <td>Supervisora:</td>
                                <td>Juana Acosta</td>
                                
                            </tr>

                        </tbody>
                        </table>
                        <div class="row" style="width: 40% !important;">
                            <div class="col-md-12">
                                <div class="col-6 col-md-12">
                                    <label class="text-left" style="margin-left: 10px;">Finaliza Practica en: 5 Meses</label>
                                </div>
                                
                                <div class="col-2 col-md-2">
                                    <a href="{{ route('evaluar-practicante.index') }}">
                                        <i class="glyph-icon tooltip-button demo-icon icon-bar-chart-o" data-original-title="EVALUAR PRACTICANTE"></i>
                                    </a>
                                </div>

                                 <div class="col-2 col-md-2">
                                    <!-- {{ route('asistencia-practicante.index') }} -->
                                    <a href="{{ url('/asistencia-practicante/'.$idseleccionado) }}">
                                        <i class="glyph-icon tooltip-button demo-icon icon-file-text-o" data-original-title="ASISTENCIA"></i>
                                    </a>
                                </div>

                                 <div class="col-2 col-md-2">
                                    <a href="{{ url('/retiro-practicante/'.$idseleccionado) }}">
                                        <i class="glyph-icon tooltip-button demo-icon icon-close" data-original-title="RETIRAR PRACTICANTE"></i>
                                    </a>
                                </div>

                                 <div class="col-2 col-md-2">
                                    <a href="{{ url('/observacion-practicante/'.$idseleccionado) }}">
                                        <i class="glyph-icon tooltip-button demo-icon icon-edit" data-original-title="OBSERVACIONES"></i>
                                    </a>
                                </div>

                                 <div class="col-2 col-md-2">
                                    <a href="#">
                                        <i class="glyph-icon tooltip-button demo-icon icon-calendar" data-original-title="HISTORIAL"></i>
                                    </a>
                                </div>

                                 <div class="col-2 col-md-2">
                                    <a href="#">
                                        <i class="glyph-icon tooltip-button demo-icon icon-clipboard" data-original-title="LEGALIZACIÓN"></i>
                                    </a>
                                </div>
                                 <div class="col-2 col-md-2">
                                    <a href="{{ url('/anexar-doc-practicantes/'.$idseleccionado) }}">
                                        <i class="glyph-icon tooltip-button demo-icon icon-upload" data-original-title="ANEXAR ARL"></i>
                                    </a>
                                </div>
                                
                            </div>
                        </div>
                            
                    </div><!-- cierre div example-box -->
                </div><!-- fin div datos personales -->
                <div class="tab-pane" id="tab2">
                    <div class="example-box-wrapper">
                        <table class="table">
                        <thead>
                        <tr>
                            <th>Nombres</th>
                            <th>Apellidos</th>
                            <th>Parentesco</th>
                            <th>Telefono Fijo</th>
                            <th>Telefono Movil</th>
                            <th>Actividad Actual</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>LISETH MARIA</td>
                                <td>JIMENEZ PEREZ</td>
                                <td>MAMÁ</td>
                                <td>3794554</td>
                                <td>3102589631 <a href="https://web.whatsapp.com/"><button class="btn btn-round btn-success"><i class="fab fa-whatsapp"></i></button></a></td>
                                <td>SECRETARIA</td>
                            </tr>
                            <tr>
                                <td>JAIRO ANDRES</td>
                                <td>PEREZ GARCIA</td>
                                <td>PAPÁ</td>
                                <td>3789562</td>
                                <td>3116547892 <a href="https://web.whatsapp.com/"><button class="btn btn-round btn-success"><i class="fab fa-whatsapp"></i></button></a></td>
                                <td>ABOGADO</td>
                            </tr>
                        </tbody>
                        </table>
                    </div>
                </div>
                <div class="tab-pane" id="tab3">
                    <div class="example-box-wrapper">
                        <table class="table">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Promedio de Notas</th>
                            <th colspan="2">Estado</th>
                            <th>Fecha Inicio</th>
                            <th>Aprobado</th>
                            <th>Reprobado</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>DISEÑO WEB</td>
                                <td>4.0</td>
                                <td>X</td>
                                <td></td>
                                <td>FINALIZADO</td>
                                <td><button class="btn btn-round btn-success"><i class="glyph-icon icon-check"></i></button></td>
                                <td>01/06/2020</td>
                            </tr>
                            <tr>
                                <td>DESARROLLO WEB</td>
                                <td>4.2</td>
                                <td>X</td>
                                <td></td>
                                <td>FINALIZADO</td>
                                <td><button class="btn btn-round btn-success"><i class="glyph-icon icon-check"></i></button></td>
                                <td>01/07/2020</td>
                            </tr>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ asset('js/estudiantesSeleccionadosInfo.js') }}"></script>
@endsection

resources/views/mensajeria.blade.php
@extends('layouts.site')

@section('title')
    Mensajeria
@endsection

@section('content')
<div id="page-title">
    <h2>Mensajeria</h2>
</div>
<div class="panel">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12 mrg20B text-right">
                <button class="btn btn-alt btn-hover btn-primary" data-target="#mdlCrear" onclick="abrirModal(this)">
                        <span>Nuevo</span>
                        <i class="glyph-icon icon-plus"></i>
                </button>
            </div>
        </div>
        {{-- Modal Creacion --}}
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="mdlCrear">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Nuevo usuario de mensajeria</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{ route('mensajeria.store') }}" id="frmCrearUserMensajeria">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Sistema de Mensajeria</label>
                                        <select name="cbSistemaMensajeria" class="form-control">
                                            <option value="">Seleccione..</option>
                                            @foreach ($sistemasMensajeria as $men)
                                                <option value="{{ $men->mensajeria_id }}">{{ $men->mensajeria_descripcion }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Usuario sistema de mensajeria</label>
                                        <input type="text" name="txtUsuario" class="form-control" autocomplete="off">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-primary" onclick="$('#frmCrearUserMensajeria').submit()">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
        {{-- Modal Creacion --}}

        {{-- Modal Editar --}}
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="mdlEditar">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Nuevo usuario de mensajeria</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{ route('mensajeria.update','') }}" id="frmEditarUserMensajeria">
                            @csrf
                            {{method_field('PUT')}}
                            <input type="hidden" name="hdUserMensajeriaId" id="hdUserMensajeriaId">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Sistema de Mensajeria</label>
                                        <select name="cbSistemaMensajeria" id="cbSistemaMensajeriaEdit" class="form-control">
                                            <option value="">Seleccione..</option>
                                            @foreach ($sistemasMensajeria as $men)
                                                <option value="{{ $men->mensajeria_id }}">{{ $men->mensajeria_descripcion }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Usuario sistema de mensajeria</label>
                                        <input type="text" name="txtUsuario" id="txtUsuarioEdit" class="form-control" autocomplete="off">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-primary" onclick="$('#frmEditarUserMensajeria').submit()">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
        {{-- Modal Editar --}}

        {{-- tabla --}}
        <div class="example-box-wrapper">
            <input type="hidden" id="hdEmpresa" value="{{ Auth::user()->tercero_id }}">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="datatable-example">
            <thead>
            <tr>
                <th>Sistema de mensajeria</th>
                <th>Usuario</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            
            </tbody>
            </table>
        </div>
        {{-- end tabla --}}
    </div>
</div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ asset('template/widgets/datatable/datatable.js') }}"></script>
    <script type="text/javascript" src="{{ asset('template/widgets/datatable/datatable-bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('template/widgets/datatable/datatable-tabletools.js') }}"></script>
    <script type="text/javascript" src="{{ asset('template/widgets/jgrowl-notifications/jgrowl.js') }}"></script>
    <script type="text/javascript" src="{{ asset('template/widgets/datepicker/datepicker.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/mensajeria.js') }}"></script>
@endsection